/* 人类问题图书馆：100 本策展书目 + 100 组人类主题词 */
const BOOKS = [
  {n:1,zh:'魔鬼出没的世界',title:'The Demon-Haunted World',author:'Carl Sagan',localCover:true,tags:['curiosity','doubt','critical','science','truth'],note:'卡尔·萨根讨论科学精神如何帮我们在谣言、迷信与伪知识之间保持清醒。'},
  {n:2,zh:'万物简史',title:'A Short History of Nearly Everything',author:'Bill Bryson',localCover:true,tags:['curiosity','wonder','science','history','life'],note:'从宇宙大爆炸走到人类出现，用故事重新点燃对世界的惊奇。'},
  {n:3,zh:'为什么',title:'The Book of Why',author:'Judea Pearl',localCover:true,tags:['curiosity','critical','decision','science','truth'],note:'从“相关”走向“因果”，学习如何提出更有力量的为什么。'},
  {n:4,zh:'思考，快与慢',title:'Thinking, Fast and Slow',author:'Daniel Kahneman',tags:['decision','critical','attention','uncertainty','wisdom'],note:'认识直觉与深思两套系统，以及它们如何共同制造判断与偏差。'},
  {n:5,zh:'侦察兵思维',title:'The Scout Mindset',author:'Julia Galef',localCover:true,tags:['doubt','critical','truth','learning','courage'],note:'不急着保卫原有立场，像侦察兵一样努力看清真实地形。'},
  {n:6,zh:'跨能致胜',title:'Range',author:'David Epstein',tags:['learning','curiosity','experimentation','work','change'],note:'在高度专业化的世界里，广泛探索与迁移能力为什么仍然重要。'},
  {n:7,zh:'黑天鹅',title:'The Black Swan',author:'Nassim Nicholas Taleb',tags:['uncertainty','decision','future','risk','critical'],note:'理解极少发生却影响巨大的事件，以及人类事后解释的冲动。'},
  {n:8,zh:'超预测',title:'Superforecasting',author:'Philip E. Tetlock',tags:['uncertainty','decision','critical','future','learning'],note:'好判断不是天赋，而是拆问题、更新概率和承认错误的习惯。'},
  {n:9,zh:'科学革命的结构',title:'The Structure of Scientific Revolutions',author:'Thomas S. Kuhn',tags:['science','history','change','truth','culture'],note:'科学并非只靠事实线性累积，也会经历范式的转换与革命。'},
  {n:10,zh:'别闹了，费曼先生',title:"Surely You're Joking, Mr. Feynman!",author:'Richard P. Feynman',tags:['curiosity','play','science','learning','experimentation'],note:'一位物理学家的顽皮人生：好奇不是姿态，而是一种亲手试试看的冲动。'},

  {n:11,zh:'创造的行为',title:'The Creative Act',author:'Rick Rubin',localCover:true,tags:['creativity','inspiration','attention','expression','craft'],note:'把创作看成一种观看世界、接收信号并不断选择的生活方式。'},
  {n:12,zh:'大魔法',title:'Big Magic',author:'Elizabeth Gilbert',tags:['creativity','inspiration','courage','play','fear'],note:'与恐惧同行，但不让恐惧坐在驾驶座上。'},
  {n:13,zh:'像艺术家一样偷师',title:'Steal Like an Artist',author:'Austin Kleon',tags:['creativity','originality','craft','learning','experimentation'],note:'原创不是凭空出现，而是在诚实吸收、转化与组合中生成。'},
  {n:14,zh:'艺术家之路',title:"The Artist's Way",author:'Julia Cameron',tags:['creativity','inspiration','expression','habit','spirituality'],note:'通过晨间书写与艺术家约会，重新打通被自我怀疑堵住的创造力。'},
  {n:15,zh:'创新公司',title:'Creativity, Inc.',author:'Ed Catmull',tags:['creativity','collaboration','leadership','trust','work'],note:'皮克斯如何保护创意、建立坦诚反馈，并让团队敢于暴露未完成。'},
  {n:16,zh:'心流',title:'Flow',author:'Mihaly Csikszentmihalyi',tags:['attention','happiness','craft','work','meaning'],note:'当挑战与能力恰好相遇，人会进入全神贯注、忘记时间的体验。'},
  {n:17,zh:'一只鸟接着一只鸟',title:'Bird by Bird',author:'Anne Lamott',tags:['craft','creativity','expression','patience','courage'],note:'面对巨大创作任务时，只写眼前这一小块，并容许糟糕的初稿存在。'},
  {n:18,zh:'艺术之战',title:'The War of Art',author:'Steven Pressfield',tags:['discipline','creativity','fear','habit','work'],note:'识别拖延、完美主义和自我怀疑组成的“阻力”。'},
  {n:19,zh:'观看之道',title:'Ways of Seeing',author:'John Berger',tags:['aesthetics','art','culture','power','attention'],note:'我们如何观看图像，也暴露了欲望、阶级、性别和权力如何塑造目光。'},
  {n:20,zh:'设计心理学',title:'The Design of Everyday Things',author:'Donald A. Norman',tags:['design','creativity','empathy','experimentation','responsibility'],note:'好的设计让行动线索清楚可见，而不是把错误都怪在使用者身上。'},

  {n:21,zh:'人类简史',title:'Sapiens',author:'Yuval Noah Harari',localCover:true,tags:['civilization','history','cooperation','culture','power'],note:'人类如何借助共同想象进行大规模合作，并重塑整个星球。'},
  {n:22,zh:'人性中的善良天使',title:'Humankind',author:'Rutger Bregman',tags:['trust','cooperation','hope','society','humanity'],note:'重新检视“人性自私”的默认叙事，寻找信任与合作的证据。'},
  {n:23,zh:'正义之心',title:'The Righteous Mind',author:'Jonathan Haidt',tags:['culture','conflict','empathy','politics','truth'],note:'不同立场的人为何真诚相信彼此冲突的道德世界。'},
  {n:24,zh:'文化地图',title:'The Culture Map',author:'Erin Meyer',tags:['culture','communication','collaboration','work','empathy'],note:'跨文化合作中，反馈、信任、时间和决策方式为何如此不同。'},
  {n:25,zh:'赋能',title:'Team of Teams',author:'Stanley McChrystal',tags:['collaboration','leadership','trust','change','responsibility'],note:'复杂环境中，透明信息与分布式决策如何让组织更灵活。'},
  {n:26,zh:'在一起',title:'Together',author:'Vivek H. Murthy',tags:['loneliness','community','belonging','care','companionship'],note:'孤独不仅是私人感受，也与健康、社区和社会结构紧密相连。'},
  {n:27,zh:'聚会的艺术',title:'The Art of Gathering',author:'Priya Parker',tags:['community','belonging','design','communication','care'],note:'一场真正有意义的相聚，需要清晰目的、边界与有意识的主持。'},
  {n:28,zh:'沃顿商学院最受欢迎的成功课',title:'Give and Take',author:'Adam Grant',tags:['cooperation','generosity','work','trust','boundaries'],note:'给予者、索取者与互利者如何塑造工作关系和长期成就。'},
  {n:29,zh:'团队协作的五大障碍',title:'The Five Dysfunctions of a Team',author:'Patrick Lencioni',tags:['collaboration','trust','conflict','leadership','responsibility'],note:'团队从建立脆弱性信任开始，才能面对冲突并共同承担结果。'},
  {n:30,zh:'非暴力沟通',title:'Nonviolent Communication',author:'Marshall B. Rosenberg',tags:['communication','empathy','conflict','boundaries','care'],note:'从评判回到观察、感受、需要和请求，让对话不再互相伤害。'},

  {n:31,zh:'依恋',title:'Attached',author:'Amir Levine',tags:['attachment','love','intimacy','anxiety','boundaries'],note:'理解不同依恋模式如何影响亲密关系里的靠近、追逐与退缩。'},
  {n:32,zh:'爱的全部',title:'All About Love',author:'bell hooks',localCover:true,tags:['love','care','justice','family','truth'],note:'爱不仅是感觉，更是一组包含照顾、承诺、信任与责任的行动。'},
  {n:33,zh:'幸福的婚姻',title:'The Seven Principles for Making Marriage Work',author:'John Gottman',tags:['marriage','communication','love','conflict','care'],note:'用长期观察研究理解伴侣如何修复冲突、维持友谊和共同意义。'},
  {n:34,zh:'紧紧抱住我',title:'Hold Me Tight',author:'Sue Johnson',tags:['attachment','intimacy','marriage','communication','vulnerability'],note:'许多争吵的深处，是“你会不会在我需要时回应我”的依恋呼喊。'},
  {n:35,zh:'少有人走的路',title:'The Road Less Traveled',author:'M. Scott Peck',tags:['love','discipline','growth','responsibility','spirituality'],note:'把爱理解为促进彼此成长的意愿，而不是短暂的迷恋感受。'},
  {n:36,zh:'爱的进化论',title:'The Course of Love',author:'Alain de Botton',tags:['romance','marriage','intimacy','forgiveness','change'],note:'小说式地写出爱情在婚后如何接受日常、误解与成熟的考验。'},
  {n:37,zh:'也许你该找个人聊聊',title:'Maybe You Should Talk to Someone',author:'Lori Gottlieb',tags:['communication','vulnerability','change','care','truth'],note:'治疗师也成为来访者，在讲述与倾听中重新看见自己的故事。'},
  {n:38,zh:'不成熟的父母',title:'Adult Children of Emotionally Immature Parents',author:'Lindsay C. Gibson',tags:['family','parenting','boundaries','loneliness','healing'],note:'辨认情感不成熟的家庭模式，并把生活的中心慢慢还给自己。'},
  {n:39,zh:'你就是孩子最好的玩具',title:'The Book You Wish Your Parents Had Read',author:'Philippa Perry',tags:['parenting','family','communication','care','healing'],note:'亲子关系不仅靠技巧，也取决于成年人如何理解自己的旧伤与反应。'},
  {n:40,zh:'爱的艺术',title:'The Art of Loving',author:'Erich Fromm',tags:['love','discipline','care','maturity','society'],note:'爱是一种需要学习与实践的能力，而不只是遇见对的人。'},

  {n:41,zh:'如她所愿',title:'Come as You Are',author:'Emily Nagoski',localCover:true,tags:['sexuality','body','desire','shame','science'],note:'用性科学理解欲望的差异、情境与压力，让身体不再被单一标准衡量。'},
  {n:42,zh:'圈养中的交配',title:'Mating in Captivity',author:'Esther Perel',tags:['sexuality','desire','marriage','intimacy','freedom'],note:'长期关系中的安全感与欲望所需的神秘、距离之间，如何保持张力。'},
  {n:43,zh:'道德浪女',title:'The Ethical Slut',author:'Dossie Easton',tags:['sexuality','consent','boundaries','desire','communication'],note:'从知情同意、诚实与边界出发讨论多元亲密关系。'},
  {n:44,zh:'性趣探秘',title:'Sex at Dawn',author:'Christopher Ryan',tags:['sexuality','history','desire','culture','science'],note:'以演化与人类学视角挑战现代社会关于性与一夫一妻的某些默认故事。'},
  {n:45,zh:'身体从未忘记',title:'The Body Keeps the Score',author:'Bessel van der Kolk',tags:['body','trauma','healing','memory','care'],note:'创伤会留在身体、注意力和关系中，恢复也需要重新获得安全与身体感。'},
  {n:46,zh:'第二性',title:'The Second Sex',author:'Simone de Beauvoir',tags:['gender','freedom','society','power','identity'],note:'追问女性如何在历史、文化与制度中被建构为“他者”。'},
  {n:47,zh:'与狼共奔的女人',title:'Women Who Run With the Wolves',author:'Clarissa Pinkola Estés',tags:['identity','body','myth','creativity','freedom'],note:'借神话与故事寻找被规训生活压低的直觉、野性和创造力。'},
  {n:48,zh:'美貌的神话',title:'The Beauty Myth',author:'Naomi Wolf',tags:['body','gender','shame','power','culture'],note:'审美标准如何成为约束女性时间、身体和自我价值的社会力量。'},
  {n:49,zh:'亲密',title:'Intimacy',author:'Osho',tags:['intimacy','vulnerability','trust','freedom','love'],note:'亲密要求袒露真实，也要求一个人拥有独处与自知的能力。'},
  {n:50,zh:'改变的意愿',title:'The Will to Change',author:'bell hooks',tags:['gender','love','vulnerability','healing','culture'],note:'讨论父权如何阻断男性的情感生命，以及爱如何成为改变的入口。'},

  {n:51,zh:'被讨厌的勇气',title:'The Courage to Be Disliked',author:'Ichiro Kishimi',localCover:true,tags:['courage','freedom','boundaries','responsibility','change'],note:'借阿德勒心理学区分彼此的课题，不再把所有人的认可当作自由前提。'},
  {n:52,zh:'活出生命的意义',title:"Man's Search for Meaning",author:'Viktor E. Frankl',localCover:true,tags:['meaning','resilience','hope','responsibility','mortality'],note:'在无法选择遭遇时，人仍可以选择态度，并为具体时刻找到意义。'},
  {n:53,zh:'沉思录',title:'Meditations',author:'Marcus Aurelius',localCover:true,tags:['wisdom','discipline','responsibility','mortality','peace'],note:'把注意力从不可控的外界收回到判断、品格与下一步行动。'},
  {n:54,zh:'脆弱的力量',title:'Daring Greatly',author:'Brené Brown',tags:['vulnerability','courage','shame','belonging','leadership'],note:'真正的勇敢不是无所畏惧，而是愿意在不确定里被看见。'},
  {n:55,zh:'不完美的礼物',title:'The Gifts of Imperfection',author:'Brené Brown',tags:['shame','belonging','confidence','care','truth'],note:'放下“应该成为谁”，练习带着不完美真实地生活。'},
  {n:56,zh:'原子习惯',title:'Atomic Habits',author:'James Clear',tags:['habit','discipline','change','identity','patience'],note:'微小行为通过系统与环境累积，身份也在一次次行动中形成。'},
  {n:57,zh:'坚毅',title:'Grit',author:'Angela Duckworth',tags:['resilience','ambition','discipline','work','patience'],note:'长期热情与坚持，如何比短期天赋更能解释某些成就。'},
  {n:58,zh:'终身成长',title:'Mindset',author:'Carol S. Dweck',tags:['learning','change','confidence','failure','growth'],note:'把能力看成可以发展，会改变我们面对挑战、反馈与失败的方式。'},
  {n:59,zh:'人生只有四千个礼拜',title:'Four Thousand Weeks',author:'Oliver Burkeman',tags:['time','mortality','work','choice','freedom'],note:'承认人生有限，不再幻想清空待办清单，而去选择值得错过其他事的事。'},
  {n:60,zh:'当下的力量',title:'The Power of Now',author:'Eckhart Tolle',tags:['mindfulness','attention','anxiety','peace','spirituality'],note:'观察念头并回到身体与此刻，松开对过去和未来的反复纠缠。'},

  {n:61,zh:'孤独的城市',title:'The Lonely City',author:'Olivia Laing',tags:['loneliness','art','city','belonging','identity'],note:'通过艺术家的生命讨论城市孤独、身体、羞耻与连接的渴望。'},
  {n:62,zh:'卿卿如晤',title:'A Grief Observed',author:'C. S. Lewis',tags:['grief','love','faith','mortality','truth'],note:'不修饰地记录丧偶之后信仰、愤怒、思念与现实感的崩塌。'},
  {n:63,zh:'当生命陷落时',title:'When Things Fall Apart',author:'Pema Chödrön',tags:['grief','fear','mindfulness','peace','compassion'],note:'不急着逃离破碎时刻，在无常和不确定里练习慈悲地停留。'},
  {n:64,zh:'另一种选择',title:'Option B',author:'Sheryl Sandberg',tags:['grief','resilience','community','hope','care'],note:'重大失去之后，个人与群体如何共同重建韧性和希望。'},
  {n:65,zh:'奇想之年',title:'The Year of Magical Thinking',author:'Joan Didion',tags:['grief','memory','love','mortality','truth'],note:'在丈夫骤逝之后，理性如何与否认、回忆和时间共同生活。'},
  {n:66,zh:'苦甜',title:'Bittersweet',author:'Susan Cain',tags:['sadness','creativity','longing','beauty','belonging'],note:'忧伤与渴望不只是负面情绪，它们也可能通向创造、连接和美。'},
  {n:67,zh:'心灵地图',title:'Atlas of the Heart',author:'Brené Brown',tags:['emotion','communication','empathy','shame','belonging'],note:'为复杂感受建立更细的语言，因为能命名，才更可能理解与表达。'},
  {n:68,zh:'情绪敏捷力',title:'Emotional Agility',author:'Susan David',tags:['emotion','change','choice','resilience','truth'],note:'不压抑也不被情绪牵走，学习让感受提供信息而非直接下命令。'},
  {n:69,zh:'正午之魔',title:'The Noonday Demon',author:'Andrew Solomon',tags:['sadness','mental-health','society','hope','science'],note:'以个人经历、研究与社会观察，呈现抑郁的复杂面貌。'},
  {n:70,zh:'越冬',title:'Wintering',author:'Katherine May',tags:['rest','change','nature','sadness','patience'],note:'低潮与停顿也是生命季节，退后、休息和越冬并非失败。'},

  {n:71,zh:'一九八四',title:'Nineteen Eighty-Four',author:'George Orwell',tags:['power','politics','truth','freedom','language'],note:'当权力控制语言、记忆与事实，个人还如何保护真实。'},
  {n:72,zh:'美丽新世界',title:'Brave New World',author:'Aldous Huxley',tags:['technology','power','desire','freedom','society'],note:'一个用快乐、消费和条件塑造维持稳定的世界，会牺牲什么。'},
  {n:73,zh:'使女的故事',title:"The Handmaid's Tale",author:'Margaret Atwood',tags:['gender','power','freedom','politics','resistance'],note:'极权制度如何占有女性身体，以及叙述本身如何保存抵抗。'},
  {n:74,zh:'极权主义的起源',title:'The Origins of Totalitarianism',author:'Hannah Arendt',tags:['politics','power','history','loneliness','truth'],note:'分析反犹主义、帝国主义与极权统治形成的历史条件。'},
  {n:75,zh:'全世界受苦的人',title:'The Wretched of the Earth',author:'Frantz Fanon',tags:['colonialism','power','violence','freedom','identity'],note:'殖民如何塑造人的身体、心理与政治，以及去殖民的激烈矛盾。'},
  {n:76,zh:'东方学',title:'Orientalism',author:'Edward W. Said',tags:['culture','power','colonialism','language','identity'],note:'“东方”如何被西方知识体系建构，并服务于权力关系。'},
  {n:77,zh:'看不见的女性',title:'Invisible Women',author:'Caroline Criado Perez',tags:['gender','data','design','justice','society'],note:'默认男性的数据缺口，如何进入交通、医疗、工作与公共设计。'},
  {n:78,zh:'新吉姆·克劳',title:'The New Jim Crow',author:'Michelle Alexander',tags:['justice','race','power','society','law'],note:'大规模监禁如何以新的制度形式延续种族等级。'},
  {n:79,zh:'美国的贫困',title:'Poverty, by America',author:'Matthew Desmond',tags:['poverty','money','justice','society','responsibility'],note:'贫困不仅是资源不足，也与富裕群体从现有制度获益的方式有关。'},
  {n:80,zh:'监视资本主义时代',title:'The Age of Surveillance Capitalism',author:'Shoshana Zuboff',tags:['technology','power','privacy','money','freedom'],note:'平台如何把行为数据变成预测与控制工具，并改变人的自主空间。'},

  {n:81,zh:'寂静的春天',title:'Silent Spring',author:'Rachel Carson',tags:['nature','science','climate','responsibility','life'],note:'农药如何进入生态链，也展示清晰科学写作推动公共改变的力量。'},
  {n:82,zh:'编织甜草',title:'Braiding Sweetgrass',author:'Robin Wall Kimmerer',tags:['nature','gratitude','science','culture','care'],note:'植物学与原住民智慧相遇，重新想象人与大地之间的互惠。'},
  {n:83,zh:'树的秘密生命',title:'The Hidden Life of Trees',author:'Peter Wohlleben',tags:['nature','communication','wonder','science','community'],note:'森林中的树木如何竞争、协作、传递信息并形成群落。'},
  {n:84,zh:'纠缠的生命',title:'Entangled Life',author:'Merlin Sheldrake',tags:['nature','science','wonder','interdependence','life'],note:'真菌让个体边界变得模糊，也重写我们对生命网络的理解。'},
  {n:85,zh:'第六次大灭绝',title:'The Sixth Extinction',author:'Elizabeth Kolbert',tags:['climate','science','mortality','responsibility','future'],note:'人类活动如何推动新的物种灭绝浪潮。'},
  {n:86,zh:'沙乡年鉴',title:'A Sand County Almanac',author:'Aldo Leopold',tags:['nature','ethics','beauty','responsibility','time'],note:'土地伦理把土壤、水、植物与动物纳入共同体。'},
  {n:87,zh:'树语',title:'The Overstory',author:'Richard Powers',tags:['nature','story','time','community','resistance'],note:'多条人类命运在树木漫长的时间尺度里汇聚。'},
  {n:88,zh:'生命 3.0',title:'Life 3.0',author:'Max Tegmark',tags:['technology','future','intelligence','responsibility','life'],note:'人工智能可能怎样改变工作、战争、意识与人类未来。'},
  {n:89,zh:'对齐问题',title:'The Alignment Problem',author:'Brian Christian',tags:['technology','ethics','intelligence','bias','responsibility'],note:'机器学习系统如何继承目标、数据与社会偏差，人类又该如何对齐它们。'},
  {n:90,zh:'浪潮将至',title:'The Coming Wave',author:'Mustafa Suleyman',tags:['technology','future','power','risk','politics'],note:'强大通用技术扩散之后，社会如何面对控制与开放的两难。'},

  {n:91,zh:'快乐之书',title:'The Book of Joy',author:'Dalai Lama',localCover:true,tags:['joy','hope','compassion','gratitude','peace'],note:'在逆境里寻找喜悦的八根支柱，包括视角、幽默、接纳与给予。'},
  {n:92,zh:'小王子',title:'The Little Prince',author:'Antoine de Saint-Exupéry',tags:['love','friendship','wonder','responsibility','loneliness'],note:'用童话重新观看成人世界、驯养、失去和真正重要的东西。'},
  {n:93,zh:'悉达多',title:'Siddhartha',author:'Hermann Hesse',tags:['spirituality','wisdom','experience','meaning','peace'],note:'一个人必须亲自穿过欲望、失落与河流，才找到不能被传授的智慧。'},
  {n:94,zh:'牧羊少年奇幻之旅',title:'The Alchemist',author:'Paulo Coelho',tags:['purpose','journey','hope','choice','wonder'],note:'追寻“天命”的寓言，也提醒人留意一路上真正学到的东西。'},
  {n:95,zh:'生命中不能承受之轻',title:'The Unbearable Lightness of Being',author:'Milan Kundera',tags:['love','choice','freedom','history','meaning'],note:'当人生只发生一次，轻与重、爱与自由的选择如何可能。'},
  {n:96,zh:'西西弗神话',title:'The Myth of Sisyphus',author:'Albert Camus',tags:['absurdity','meaning','choice','freedom','mortality'],note:'当世界不给出终极答案，人是否仍能清醒而热烈地活。'},
  {n:97,zh:'瓦尔登湖',title:'Walden',author:'Henry David Thoreau',tags:['nature','simplicity','freedom','attention','society'],note:'通过主动简朴的生活，检验什么是真正必要。'},
  {n:98,zh:'静止的艺术',title:'The Art of Stillness',author:'Pico Iyer',tags:['stillness','attention','travel','peace','time'],note:'在持续加速的世界里，不动也可以是一种更深的远行。'},
  {n:99,zh:'小熊维尼的道',title:'The Tao of Pooh',author:'Benjamin Hoff',tags:['wisdom','simplicity','joy','spirituality','play'],note:'借小熊维尼的故事，把道家的顺其自然讲得轻盈可亲。'},
  {n:100,zh:'禅与摩托车维修艺术',title:'Zen and the Art of Motorcycle Maintenance',author:'Robert M. Pirsig',tags:['quality','philosophy','craft','journey','truth'],note:'一场公路旅行与思想探险，追问“良质”如何连接技术、艺术和生活。'}
];

const themeRows = [
  ['curiosity','好奇',['好奇','为什么','怎么回事','想知道','多少本书','到底有多少'],'好奇不是没完没了地问，它是你与世界保持联系的方式。'],
  ['wonder','惊奇',['惊奇','惊讶','震撼','神奇','不可思议','哇'],'成年并不意味着必须对一切习以为常。'],
  ['doubt','怀疑',['怀疑','不相信','真的吗','质疑','骗人','可疑'],'好的怀疑不是拒绝相信，而是愿意让证据改变自己。'],
  ['critical','批判思考',['批判','逻辑','谣言','真相','思考能力','独立思考'],'先检查判断的地基，再决定要不要住进这个结论。'],
  ['learning','学习',['学习','读书','知识','考试','学不会','理解'],'学习不是把答案装进脑子，而是让问题变得更清楚。'],
  ['memory','记忆',['记忆','忘记','记不住','回忆','过去','想起来'],'记忆不是录像，它也在不断重写我们是谁。'],
  ['attention','注意力',['注意','专注','分心','手机','集中','走神'],'注意力投向哪里，生活就在你那里发生。'],
  ['decision','决策',['选择困难','决定','选哪个','纠结','判断','抉择'],'决定不是等到毫无疑问，而是看清代价后愿意承担。'],
  ['uncertainty','不确定',['不确定','未知','没把握','风险','意外','变化太快'],'不确定不是知识的失败，而是现实本来的形状。'],
  ['wisdom','智慧',['智慧','聪明','通透','开悟','人生经验','道理'],'智慧常常不是知道更多，而是知道什么可以先放下。'],

  ['creativity','创造',['创造','创作','共创','做东西','点子','创意'],'创造不是等待闪电，而是持续给微小信号一张桌子。'],
  ['inspiration','灵感',['灵感','没灵感','启发','找感觉','脑洞','想法'],'灵感偏爱正在工作的人，也偏爱愿意四处观看的人。'],
  ['imagination','想象',['想象','幻想','脑补','异想天开','未来画面','白日梦'],'想象力让现实之外的可能，先在心里获得一次试演。'],
  ['play','玩耍',['玩','游戏','有趣','好玩','玩心','玩耍'],'玩不是正事的反面，它是探索不必立刻有用的可能。'],
  ['craft','手艺',['手艺','技术','练习','打磨','基本功','熟练'],'手艺是热爱愿意接受重复之后，留下的形状。'],
  ['expression','表达',['表达','说不出来','写作','画画','唱歌','创作欲'],'表达不是证明自己正确，而是让内在经验有机会被看见。'],
  ['aesthetics','审美',['审美','美感','好看','丑','品味','艺术感'],'审美不是装饰，它决定了我们愿意注意和珍惜什么。'],
  ['design','设计',['设计','用户体验','产品','界面','解决问题','好用'],'设计是在看见别人的行动之后，对环境做出温柔的安排。'],
  ['experimentation','实验',['实验','试试看','尝试','原型','测试','失败了再来'],'实验把“我行不行”改写成“这样做会发生什么”。'],
  ['originality','原创',['原创','抄袭','独特','与众不同','自己的风格','模仿'],'原创往往不是无中生有，而是诚实地暴露你的组合方式。'],

  ['cooperation','合作',['合作','共进','一起做','互助','配合','协作'],'合作不是每个人都一样，而是差异能朝同一个方向用力。'],
  ['collaboration','共创',['共创','团队创作','共同完成','集体智慧','一起想','头脑风暴'],'真正的共创允许半成品被看见，也允许好点子没有固定主人。'],
  ['solidarity','团结',['团结','联合','站在一起','同盟','齐心','共同体'],'团结不是消除分歧，而是在重要问题上决定彼此不孤立。'],
  ['trust','信任',['信任','不信任','被骗','可靠','承诺','安全感'],'信任不是确定不会受伤，而是知道破裂之后仍可谈论与修复。'],
  ['communication','沟通',['沟通','聊天','说话','吵架','解释','听不懂'],'沟通的难处不在于发出声音，而在于让需要穿过评判。'],
  ['belonging','归属',['归属','不合群','融不进去','属于哪里','格格不入','被接纳'],'归属不是削去不同，而是在不同仍然存在时被允许留下。'],
  ['companionship','陪伴',['陪伴','陪我','有人在','一起待着','守着','身边有人'],'好的陪伴不急着消灭痛苦，它先让痛苦不必独自发生。'],
  ['friendship','友谊',['朋友','友情','友谊','知己','绝交','被朋友抛弃'],'友谊不是永不失望，而是彼此愿意把关系当成可以修复的东西。'],
  ['community','社群',['社群','社区','群体','圈子','邻居','大家'],'社区始于人们愿意对彼此的生活多承担一点点。'],
  ['leadership','领导',['领导','带团队','管理','负责人','带领','组织'],'领导不是永远有答案，而是创造别人敢说真话的条件。'],

  ['love','爱',['爱','爱情','喜欢一个人','被爱','我爱他','我爱她'],'爱既是感受，也是重复发生的照顾、尊重与责任。'],
  ['romance','浪漫',['浪漫','约会','恋爱','心动','暧昧','表白'],'浪漫让日常短暂发光，但关系还要学习如何安放平凡。'],
  ['intimacy','亲密',['亲密','靠近','亲近','秘密','坦诚','深入关系'],'亲密不是没有边界，而是边界之内可以诚实地显露自己。'],
  ['attachment','依恋',['依恋','粘人','回避','患得患失','安全型','离不开'],'你在关系里的追逐或退缩，也许是旧的安全策略在工作。'],
  ['family','亲情',['亲情','家人','家庭','父母','兄弟姐妹','家'],'家庭给人最早的语言，也可能留下最难命名的沉默。'],
  ['parenting','亲子',['孩子','父母','育儿','亲子','妈妈','爸爸'],'养育孩子也会唤醒成人曾经没有被照顾的部分。'],
  ['marriage','婚姻',['婚姻','结婚','夫妻','老公','老婆','伴侣'],'婚姻不是爱情的毕业典礼，而是一门持续协商现实的课程。'],
  ['heartbreak','失恋',['失恋','分手','被抛弃','离开我','前任','心碎'],'关系结束说明一段共同生活停止了，不说明你的价值停止了。'],
  ['forgiveness','宽恕',['原谅','宽恕','放下仇恨','释怀','记恨','和解'],'宽恕不是替伤害开脱，而是不再让它继续管理你的今天。'],
  ['care','温暖',['温暖','照顾','关心','善意','体贴','呵护'],'温暖很少宏大，它常藏在“我记得你需要什么”里面。'],

  ['desire','欲望',['欲望','渴望','想要','贪心','冲动','上瘾'],'欲望不是敌人；听懂它在要什么，比立刻服从或压抑更重要。'],
  ['sexuality','性爱',['性爱','性欲','性生活','性关系','性','做爱'],'性既属于身体，也被安全、文化、关系和自我感共同塑造。'],
  ['body','身体',['身体','身材','健康','外貌','胖','瘦'],'身体不是供你终身审判的物件，而是你体验世界的居所。'],
  ['shame','羞耻',['羞耻','丢人','自卑','见不得人','羞愧','不敢被看见'],'羞耻说“你本身有问题”，而修复从把人与错误分开开始。'],
  ['consent','同意',['同意','拒绝','边界感','强迫','不愿意','尊重意愿'],'真正的同意应当清楚、自愿、持续，而且随时可以撤回。'],
  ['passion','激情',['激情','热烈','热情','燃烧','冲动','着迷'],'激情提供能量，但方向需要价值与现实共同校准。'],
  ['gender','性别',['性别','女性','男性','男权','女权','性别角色'],'许多被说成“天生如此”的事，其实也有制度和文化的手笔。'],
  ['identity','身份',['身份','我是谁','自我认同','角色','标签','做自己'],'身份既是你选择的故事，也受到别人如何命名你的影响。'],
  ['vulnerability','脆弱',['脆弱','软弱','暴露','不设防','怕受伤','敏感'],'脆弱不是勇气的反面，而是勇气发生时必须经过的门。'],
  ['boundaries','边界',['边界','底线','拒绝','说不','越界','讨好'],'边界不是把人推出去，而是说明怎样靠近才不会彼此耗尽。'],

  ['courage','勇气',['勇气','勇敢','不敢','胆小','害怕尝试','迈出去'],'勇气不是恐惧消失，而是有更重要的东西值得带着恐惧前进。'],
  ['confidence','自信',['自信','没自信','自我怀疑','不如别人','能力','相信自己'],'自信不必先成为感觉，也可以是一次次守住对自己的承诺。'],
  ['freedom','自由',['自由','束缚','限制','做主','独立','解放'],'自由不仅是没有约束，也是愿意承担选择所带来的后果。'],
  ['discipline','自律',['自律','坚持','拖延','懒惰','执行力','管不住自己'],'自律比意志更依赖环境，也比惩罚更需要清楚的方向。'],
  ['habit','习惯',['习惯','每天','戒掉','养成','重复','规律'],'习惯是投票：每一次微小行动，都在支持你想成为的那个人。'],
  ['ambition','野心',['野心','成功','成就','上进','赢','出人头地'],'野心可以推你向前，也值得追问：终点是谁替你画的。'],
  ['purpose','目标',['目标','方向','理想','想做什么','人生规划','目的'],'目标给行动方向，但不必把人的全部价值抵押给抵达。'],
  ['responsibility','责任',['责任','负责','义务','担当','应该做','后果'],'责任不是把一切揽下，而是准确认领真正属于你的部分。'],
  ['resilience','力量',['力量','坚强','韧性','撑下去','扛过去','重新站起来'],'韧性不是恢复成从未受伤的样子，而是带着变化继续生长。'],
  ['change','改变',['改变','转变','重新开始','来不及了','改不了','新的生活'],'改变常常先以笨拙出现；不熟练不等于方向错误。'],

  ['happiness','快乐',['快乐','开心','高兴','幸福','舒服','满足'],'快乐不需要通过“有用”获得许可，普通的一天也可以发亮。'],
  ['joy','喜悦',['喜悦','欢喜','雀跃','欣喜','乐呵','哈哈'],'喜悦不否认痛苦，它只是证明心仍有伸展的空间。'],
  ['sadness','难过',['难过','伤心','想哭','低落','痛苦','崩溃'],'难过往往说明某些东西对你重要，它不必被立刻修好。'],
  ['anger','愤怒',['愤怒','生气','气死','烦死','妈的','操你'],'愤怒常替边界披上盔甲，先听听盔甲里面在保护什么。'],
  ['fear','恐惧',['恐惧','害怕','怕死','不敢','可怕','吓人'],'恐惧会放大危险，但也可能在提醒你做好准备、寻求陪伴。'],
  ['anxiety','焦虑',['焦虑','担心','压力','紧张','怎么办','做不好'],'焦虑把未来剪成灾难片；你只需要负责眼前可行动的一格。'],
  ['loneliness','孤独',['孤独','孤单','没人理解','寂寞','一个人','空空的'],'孤独不是不合群，它是在提醒你渴望一种更真实的连接。'],
  ['boredom','无聊',['无聊','没劲','没事干','好闲','发呆','什么都不想做'],'无聊是注意力暂时没有决定要爱什么，不必立刻用信息填满。'],
  ['envy','嫉妒',['嫉妒','羡慕','眼红','凭什么他','比较','酸'],'嫉妒并不体面，却可能诚实指出你未被承认的渴望。'],
  ['grief','哀伤',['哀伤','去世','死亡','失去亲人','永别','丧亲'],'哀伤不是要被完成的任务，而是爱失去去处之后的新形状。'],

  ['justice','正义',['正义','公平','不公平','公道','维权','歧视'],'正义不仅问谁做错了，也问规则让谁长期承担代价。'],
  ['power','权力',['权力','控制','服从','压迫','掌控','支配'],'权力最值得警惕的时候，往往是它把自己的存在伪装成常识。'],
  ['equality','平等',['平等','不平等','特权','弱势','平权','机会'],'平等不是假装差异不存在，而是让差异不再决定谁更有资格。'],
  ['conflict','冲突',['冲突','矛盾','争执','战争','对立','吵架'],'冲突不一定意味着关系失败，它也可能暴露必须谈判的现实。'],
  ['culture','文化',['文化','传统','习俗','价值观','代沟','跨文化'],'文化像空气：身在其中时最难看见，却持续塑造判断。'],
  ['prejudice','偏见',['偏见','刻板印象','歧视','地域黑','种族','标签化'],'偏见让我们在认识一个人之前，就错把分类当成答案。'],
  ['work','工作',['工作','上班','职业','同事','老板','职场'],'工作可以承载意义，但不该垄断一个人的全部身份。'],
  ['money','金钱',['金钱','钱','赚钱','贫穷','富有','消费'],'钱既是资源，也是关系、自由和安全感的一种社会语言。'],
  ['poverty','贫困',['贫困','穷','没钱','底层','生存','房租'],'贫困不是个人品格的缺陷，它也由机会、制度和资源分配塑造。'],
  ['politics','政治',['政治','国家','政府','制度','公共','选举'],'政治并不只在远处，它也存在于谁能决定、谁被迫承受。'],

  ['nature','自然',['自然','森林','树','山川','动物','大地'],'自然不是生活的背景板，我们本来就是它相互依赖的一部分。'],
  ['science','科学',['科学','宇宙','物理','生物','研究','证据'],'科学的力量不只在答案，更在一套公开纠错的方法。'],
  ['technology','科技',['科技','技术','人工智能','AI','互联网','机器'],'技术会放大某种价值，因此“能不能”之后还必须问“该不该”。'],
  ['future','未来',['未来','以后','将来','趋势','预言','下一代'],'未来不是一处等着抵达的地方，它也在今天的制度与选择里生成。'],
  ['climate','气候',['气候','环保','生态','污染','地球','灭绝'],'气候问题要求我们把时间尺度拉长，也把责任半径放大。'],
  ['life','生命',['生命','活着','生物','出生','存在','活力'],'生命从不是孤立个体，它靠无数看得见和看不见的关系维持。'],
  ['mortality','死亡',['死亡','死','终点','有限','临终','老去'],'想到死亡并不一定使生活变暗，它也会让选择获得轮廓。'],
  ['time','时间',['时间','来不及','年龄','岁月','过去未来','拖延'],'时间管理的深处不是塞进更多，而是承认你终究要错过一些。'],
  ['history','历史',['历史','以前','古代','过去','时代','文明史'],'历史不是过去的仓库，它是今天许多“理所当然”的来路。'],
  ['civilization','文明',['文明','人类','社会演化','国家起源','共同想象','现代性'],'文明依赖共同故事，也必须不断追问这些故事服务了谁。'],

  ['meaning','意义',['意义','活着为了什么','人生意义','值得吗','没意义','为什么活'],'意义不是宇宙统一发放的答案，而是你对具体生活的回应。'],
  ['absurdity','荒诞',['荒诞','无意义','可笑','徒劳','虚无','西西弗'],'世界未必回答我们，但人仍可以清醒地选择如何活。'],
  ['faith','信仰',['信仰','相信','上帝','宗教','祈祷','神'],'信仰可能提供归属与方向，也值得与怀疑保持诚实对话。'],
  ['spirituality','精神性',['精神','灵性','禅','道','内在','超越'],'精神生活不是逃离现实，而是改变你与现实相处的姿势。'],
  ['mindfulness','觉察',['觉察','当下','正念','冥想','呼吸','活在现在'],'觉察不是停止思想，而是看见思想正在发生。'],
  ['peace','平静',['平静','平和','安宁','静下来','内心安定','不烦躁'],'平静并非没有风浪，而是不再让每阵风都替你决定方向。'],
  ['hope','希望',['希望','盼望','会好吗','期待','曙光','还有救'],'希望不是预测事情一定顺利，而是相信行动仍然有意义。'],
  ['choice','选择',['选择','选项','另一条路','后悔','重来','决定人生'],'选择之所以沉重，是因为它既打开道路，也关闭其他道路。'],
  ['truth','真实',['真实','真话','诚实','事实','撒谎','本质'],'真实不总让人舒服，但它让下一步建立在不会突然塌陷的地面上。'],
  ['stillness','安静',['安静','静止','独处','慢下来','停一停','休息'],'停下来不是退出世界，而是重新听见被速度盖住的声音。']
];

const THEMES = themeRows.map((row, index) => ({
  index: index + 1, id: row[0], label: row[1], words: row[2], line: row[3]
}));

const DOMAIN_NAMES = {
  mind:'认知与好奇', create:'创造与表达', connect:'连接与合作', love:'爱与家庭',
  body:'身体与亲密', self:'成长与行动', emotion:'情绪与感受', society:'社会与权力',
  world:'世界与未来', existence:'存在与意义'
};

const DOMAIN_BY_INDEX = i => ['mind','create','connect','love','body','self','emotion','society','world','existence'][Math.floor(i / 10)];
THEMES.forEach((theme, i) => theme.domain = DOMAIN_BY_INDEX(i));

const DOMAIN_RESPONSES = {
  mind: ['你的问题像是在轻轻敲世界的外壳，想知道里面还有什么。','你不是问得太多，而是在拒绝把“理所当然”当作终点。','这是一种认知上的痒：答案重要，但更好的问题也许更重要。'],
  create: ['你现在需要的可能不是一个完美点子，而是一块允许试错的小地方。','创造常从不完整开始，随后才慢慢认出自己的方向。','先让东西出现，再让判断入场；顺序反过来，灵感很容易窒息。'],
  connect: ['这个问题里不只有“我”，也有“我们怎样一起”。','人与人真正靠近，通常不是因为完全一致，而是差异仍能被放在桌面上。','关系不是读心术，它需要清楚的信号、耐心和修复。'],
  love: ['亲密的问题很少只有对错，它常同时牵动需要、恐惧和旧经验。','你在问一个人，也在问自己如何爱、如何被爱。','爱会发光，也会把各自没有照顾好的部分照出来。'],
  body: ['身体知道的事情，有时比语言更早。','欲望、边界和安全感可以同时被认真对待，它们不必互相取消。','身体不是抽象道德题，它有节奏、历史，也有说“不”的权利。'],
  self: ['你想改变的愿望已经出现了，但不必用羞辱自己来给它加速。','成长不是把旧的自己开除，而是给它多一种选择。','下一步不必伟大，只要足够具体，能由今天的你完成。'],
  emotion: ['先不要急着把感受改掉；它可能正在传递一条重要消息。','情绪不是法官，却是一位很响的信使。','你可以听见这份感受，而不必把方向盘完全交给它。'],
  society: ['这不只是一件私人的事，它也与规则、资源和谁有决定权有关。','当个人问题反复出现在很多人身上，我们就该看看结构。','理解权力不是为了变得犬儒，而是为了知道改变可以从哪里发生。'],
  world: ['把视角拉远之后，你的问题会连上更长的时间和更大的生命网络。','世界不是静止背景；人、技术与自然一直在互相改写。','知道得越多，责任未必更轻，但选择会更清楚。'],
  existence: ['这个问题没有标准答案，但它值得被认真地活一遍。','有些问题不是为了结束思考，而是为了陪我们穿过一段人生。','当终极答案缺席时，你仍可以用具体选择回答今天。']
};
